name: Cargo Lint
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Remove unnecessary WASM build artifacts
  WASM_BUILD_CLEAN_TARGET: 1
  # Stripping symbols and optimizing for binary size
  RUSTFLAGS: -C strip=symbols -C opt-level=s

jobs:
  cargo-lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: 🚧 Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ⚙️ Install rust compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev libclang-dev

      - name: 🦿 Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: 1.94.1

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: lint-and-test
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: 🧭 Run cargo lint & clippy
        run: cargo fmt -- --check && cargo clippy -- -D warnings
