name: Cargo lint
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Remove unnecessary WASM build artifacts
  WASM_BUILD_CLEAN_TARGET: 1
  # Stripping symbols and optimizing for binary size
  RUSTFLAGS: -C strip=symbols -C opt-level=s

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: 🚧 Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ⚙️ Install rust compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libudev-dev

      - name: 👨‍🔧 Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 20

      - name: 🦿 Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly

      - name: 🧠 Cache Rust dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: 🧭 Run cargo lint
        run: cargo fmt -- --check && cargo clippy -- -D warnings
